export * from './assetInvestigationController.service';
import { AssetInvestigationControllerService } from './assetInvestigationController.service';
export * from './auctionBiddingController.service';
import { AuctionBiddingControllerService } from './auctionBiddingController.service';
export * from './auctionController.service';
import { AuctionControllerService } from './auctionController.service';
export * from './auctionDebtSettlementController.service';
import { AuctionDebtSettlementControllerService } from './auctionDebtSettlementController.service';
export * from './auctionDocumentController.service';
import { AuctionDocumentControllerService } from './auctionDocumentController.service';
export * from './auctionExpenseController.service';
import { AuctionExpenseControllerService } from './auctionExpenseController.service';
export * from './auctionLitigationCaseController.service';
import { AuctionLitigationCaseControllerService } from './auctionLitigationCaseController.service';
export * from './configurationController.service';
import { ConfigurationControllerService } from './configurationController.service';
export * from './convenienceChequeController.service';
import { ConvenienceChequeControllerService } from './convenienceChequeController.service';
export * from './conveyanceController.service';
import { ConveyanceControllerService } from './conveyanceController.service';
export * from './courtController.service';
import { CourtControllerService } from './courtController.service';
export * from './courtTrialController.service';
import { CourtTrialControllerService } from './courtTrialController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './debtSettlementAccountController.service';
import { DebtSettlementAccountControllerService } from './debtSettlementAccountController.service';
export * from './defermentController.service';
import { DefermentControllerService } from './defermentController.service';
export * from './defermentExecController.service';
import { DefermentExecControllerService } from './defermentExecController.service';
export * from './dimsController.service';
import { DimsControllerService } from './dimsController.service';
export * from './documentController.service';
import { DocumentControllerService } from './documentController.service';
export * from './documentTempController.service';
import { DocumentTempControllerService } from './documentTempController.service';
export * from './dopaController.service';
import { DopaControllerService } from './dopaController.service';
export * from './exReportController.service';
import { ExReportControllerService } from './exReportController.service';
export * from './expenseController.service';
import { ExpenseControllerService } from './expenseController.service';
export * from './financialController.service';
import { FinancialControllerService } from './financialController.service';
export * from './litigationCaseController.service';
import { LitigationCaseControllerService } from './litigationCaseController.service';
export * from './litigationController.service';
import { LitigationControllerService } from './litigationController.service';
export * from './masterDataController.service';
import { MasterDataControllerService } from './masterDataController.service';
export * from './noticeController.service';
import { NoticeControllerService } from './noticeController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './payCourtFeeController.service';
import { PayCourtFeeControllerService } from './payCourtFeeController.service';
export * from './phonebookController.service';
import { PhonebookControllerService } from './phonebookController.service';
export * from './preferenceController.service';
import { PreferenceControllerService } from './preferenceController.service';
export * from './profileDirectController.service';
import { ProfileDirectControllerService } from './profileDirectController.service';
export * from './receiveController.service';
import { ReceiveControllerService } from './receiveController.service';
export * from './seizureController.service';
import { SeizureControllerService } from './seizureController.service';
export * from './seizureFeeController.service';
import { SeizureFeeControllerService } from './seizureFeeController.service';
export * from './seizureLitigationCaseController.service';
import { SeizureLitigationCaseControllerService } from './seizureLitigationCaseController.service';
export * from './seizureLitigationController.service';
import { SeizureLitigationControllerService } from './seizureLitigationController.service';
export * from './taskController.service';
import { TaskControllerService } from './taskController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './userControllerV2.service';
import { UserControllerV2Service } from './userControllerV2.service';
export * from './withdrawSeizureController.service';
import { WithdrawSeizureControllerService } from './withdrawSeizureController.service';
export * from './withdrawWritOfExecController.service';
import { WithdrawWritOfExecControllerService } from './withdrawWritOfExecController.service';
export * from './workbenchController.service';
import { WorkbenchControllerService } from './workbenchController.service';
export * from './writOfExecController.service';
import { WritOfExecControllerService } from './writOfExecController.service';
export const APIS = [AssetInvestigationControllerService, AuctionBiddingControllerService, AuctionControllerService, AuctionDebtSettlementControllerService, AuctionDocumentControllerService, AuctionExpenseControllerService, AuctionLitigationCaseControllerService, ConfigurationControllerService, ConvenienceChequeControllerService, ConveyanceControllerService, CourtControllerService, CourtTrialControllerService, CustomerControllerService, DebtSettlementAccountControllerService, DefermentControllerService, DefermentExecControllerService, DimsControllerService, DocumentControllerService, DocumentTempControllerService, DopaControllerService, ExReportControllerService, ExpenseControllerService, FinancialControllerService, LitigationCaseControllerService, LitigationControllerService, MasterDataControllerService, NoticeControllerService, NotificationControllerService, PayCourtFeeControllerService, PhonebookControllerService, PreferenceControllerService, ProfileDirectControllerService, ReceiveControllerService, SeizureControllerService, SeizureFeeControllerService, SeizureLitigationCaseControllerService, SeizureLitigationControllerService, TaskControllerService, UserControllerService, UserControllerV2Service, WithdrawSeizureControllerService, WithdrawWritOfExecControllerService, WorkbenchControllerService, WritOfExecControllerService];
