export type LogType = 'CUSTOMER' | 'LITIGATION' | 'TASK' | 'FINANCE_EXPENSE' | 'FINANCE_RECEIPT' | 'FINANCE_ADVANCE';
export const LogType = {
  CUSTOMER: 'CUSTOMER' as LogType,
  LITIGATION: 'LITIGATION' as LogType,
  TASK: 'TASK' as LogType,
  FINANCE_EXPENSE: 'FINANCE_EXPENSE' as LogType,
  FINANCE_RECEIPT: 'FINANCE_RECEIPT' as LogType,
  FINANCE_ADVANCE: 'FINANCE_ADVANCE' as LogType,
};
