import { TASK_ROUTES } from '.';
import { taskCode } from '../models/task.model';

// For mvp2, mvp3
export const TaskRoutingMapper = new Map<taskCode, string>([
  // EXECUTION_WARRANT
  [taskCode.R2E04_01_2B, TASK_ROUTES.EXECUTION_WARRANT],
  [taskCode.R2E04_02_2A, TASK_ROUTES.EXECUTION_WARRANT],
  [taskCode.R2E04_03_3A, TASK_ROUTES.EXECUTION_WARRANT],
  // SEIZURE_PROPERTY
  [taskCode.R2E05_01_2D, TASK_ROUTES.COMMAND],
  [taskCode.R2E05_02_3C, TASK_ROUTES.COMMAND],
  [taskCode.R2E05_03_3D, TASK_ROUTES.COMMAND],
  [taskCode.R2E05_03_4, TASK_ROUTES.SEIZURE_PROPERTY],
  [taskCode.R2E05_04_4, TASK_ROUTES.SEIZURE_PROPERTY],
  [taskCode.R2E05_06_3F, TASK_ROUTES.COMMAND],
  [taskCode.R2E05_09_4, TASK_ROUTES.NON_PLEDGE],
  [taskCode.R2E05_10_5, TASK_ROUTES.SEIZURE_PROPERTY],
  // WITHDRAWN_SEIZURE_PROPERTY
  [taskCode.R2E06_01_A, TASK_ROUTES.WITHDRAWN_SEIZURE_PROPERTY],
  [taskCode.R2E06_02_B, TASK_ROUTES.WITHDRAWN_SEIZURE_PROPERTY],
  [taskCode.R2E06_03_C, TASK_ROUTES.WITHDRAWN_SEIZURE_PROPERTY],
  [taskCode.R2E06_04_D, TASK_ROUTES.WITHDRAWN_SEIZURE_PROPERTY],
  [taskCode.R2E06_05_E, TASK_ROUTES.WITHDRAWN_SEIZURE_PROPERTY],
  // WITHDRAWN_WRIT_OF_EXECUTION
  [taskCode.R2E06_10, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  [taskCode.R2E06_11_A, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  [taskCode.R2E06_12_B, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  [taskCode.R2E06_13_C, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  [taskCode.R2E06_14_D, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  [taskCode.R2E06_15_E, TASK_ROUTES.WITHDRAWN_WRIT_OF_EXECUTION],
  // PUBLIC AUCTION SP4
  [taskCode.R2E09_00_1A, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_00_01_1A, TASK_ROUTES.PUBLIC_AUCTION], //SP8 enhancment LEX2-26737
  [taskCode.R2E09_02_3B, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_06_7C, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_04_01_11, `${TASK_ROUTES.PUBLIC_AUCTION}/auction-result-info`],
  [taskCode.R2E09_06_12C, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_05_01_12A, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_08_01_3_1, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_11_01, TASK_ROUTES.PUBLIC_AUCTION_OWNER_TRNASFER],
  [taskCode.R2E05_561_A_MOCK, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_10_01, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_10_02, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_10_03, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_06_03, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_09_01_13_1, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_09_03_14_1, TASK_ROUTES.PUBLIC_AUCTION],
  [taskCode.R2E09_06_04_6, TASK_ROUTES.PUBLIC_AUCTION_OWNER_TRNASFER],
  // seizure-fee upload receipts for non e-filing
  [taskCode.R2E35_01_E05_01_6A, TASK_ROUTES.SEIZURE_UPLOAD_RECEIPT],
  [taskCode.R2E35_01_E05_02_6B, TASK_ROUTES.SEIZURE_UPLOAD_RECEIPT],
  // auction-expense upload receipts for non e-filing
  [taskCode.R2E35_02_E09_01_7A, TASK_ROUTES.PUBLIC_AUCTION_ADVANCE_PAYMENT],
  [taskCode.R2E35_02_E09_02_7B, TASK_ROUTES.PUBLIC_AUCTION_ADVANCE_PAYMENT],
  [taskCode.R2E09_14_3C, TASK_ROUTES.PUBLIC_AUCTION_ADVANCE_PAYMENT],
  // none-plege
  [taskCode.R2E05_08_3A, TASK_ROUTES.NON_PLEDGE],
  [taskCode.R2_LEX2_463_MOCK, TASK_ROUTES.COMMAND],

  [taskCode.R2E05_07_2A, TASK_ROUTES.NON_PLEDGE],
  // Asset Investigation
  [taskCode.R2E03_01_01, TASK_ROUTES.INVESTIGATES_PROPERTY],
  // Preference
  [taskCode.EXECUTE_PREFERENCE, TASK_ROUTES.PREFERENCE],
  [taskCode.ASSIGN_LAWYER_PLAINTIFF_CASE, TASK_ROUTES.PREFERENCE],
  [taskCode.PREPARE_PREFERENCE_DODUMENT, TASK_ROUTES.PREFERENCE],

]);
