/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountList } from './accountList';


export interface AccountListReportDto { 
    customerDetail?: string;
    dataDateTime?: string;
    viewerDetail?: string;
    accountList?: Array<AccountList>;
}

