/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountSummary { 
    accountNumber?: string;
    accountStatus?: string;
    cclassAging?: string;
    cclassCondition?: string;
    creditLimit?: number;
    firstDisbursementDate?: string;
    lastPaymentDate?: string;
    ledgerBalance?: number;
    legalStatus?: string;
    marketCode?: string;
    maturityDate?: string;
    openAccountDate?: string;
    payoffAmount?: number;
    productType?: string;
    subAccountOptions?: string;
}

