/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvancePaymentInquiryRequest { 
    tab?: string;
    advancePaymentNo?: string;
    advancePaymentStatus?: string;
    user?: string;
    searchString?: string;
}

