/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdvancePaymentDto { 
    taskId?: number;
    taskCode?: string;
    taskName?: string;
    statusCode?: string;
    statusName?: string;
    runningNumber?: number;
    advancePaymentNo?: string;
    advancePaymentAmount?: number;
    responseUser?: string;
    advancePaymentStatus?: string;
    advancePaymentStatusName?: string;
    currentAssigneeId?: string;
    currentAssigneeName?: string;
}

