/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetInvestigationDto } from './assetInvestigationDto';


export interface AssetInvestigationLitigationCase { 
    litigationCaseId?: number;
    litigationCaseSeqNo?: number;
    blackCaseNo?: string;
    redCaseNo?: string;
    assetInvestigations?: Array<AssetInvestigationDto>;
}

