/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetInvestigationPersonUpdate } from './assetInvestigationPersonUpdate';
import { AssetInvestigationPersonDocumentUpload } from './assetInvestigationPersonDocumentUpload';


export interface AssetInvestigationSaveRequest { 
    action?: AssetInvestigationSaveRequest.ActionEnum;
    litigationDocumentUpload?: Array<AssetInvestigationPersonDocumentUpload>;
    personUpdate?: Array<AssetInvestigationPersonUpdate>;
    reasonCode?: string;
    remark?: string;
}
export namespace AssetInvestigationSaveRequest {
    export type ActionEnum = 'DRAFT' | 'SUBMIT' | 'APPROVE' | 'REJECT' | 'CANCEL' | 'DELETE' | 'UPDATE' | 'SUBMIT1' | 'SUBMIT2' | 'SAVE';
    export const ActionEnum = {
        Draft: 'DRAFT' as ActionEnum,
        Submit: 'SUBMIT' as ActionEnum,
        Approve: 'APPROVE' as ActionEnum,
        Reject: 'REJECT' as ActionEnum,
        Cancel: 'CANCEL' as ActionEnum,
        Delete: 'DELETE' as ActionEnum,
        Update: 'UPDATE' as ActionEnum,
        Submit1: 'SUBMIT1' as ActionEnum,
        Submit2: 'SUBMIT2' as ActionEnum,
        Save: 'SAVE' as ActionEnum
    };
}


