/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetInvestigationDto { 
    assetInvestigationId?: number;
    assetInvestigationRound?: number;
    submittedTimestamp?: string;
    resultTimestamp?: string;
    reasonCode?: string;
    reasonDesc?: string;
    totalPersons?: number;
    totalAssets?: number;
    status?: string;
    statusName?: string;
}

