/**
 * KTB Backend for Frontend APIs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionCashierChequeStampDutyValidateRequest { 
    aucBiddingId?: number;
    aucRef?: number;
    deedGroupIdList?: Array<number>;
    deedGroupSoldDate?: string;
}

