/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionDeedInfoResponse { 
    saleTypeDesc?: string;
    reserveFund?: number;
    reserveFund1?: number;
    assetPrice2?: number;
    assetPrice3?: number;
    assetPrice4?: number;
    assetPrice5?: number;
    totalDeeds?: number;
}

