/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionAnnounceSearchConditionRequest { 
    aucLot?: string;
    aucSet?: string;
    fbidnum?: string;
    redCaseNo?: string;
    lawCourtName?: string;
    defendantName?: string;
    matchingStatus?: string;
    aucStatus?: Array<string>;
    isNonPledgeAsset?: boolean;
}

