/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuctionDetailsAssetOwner } from './auctionDetailsAssetOwner';
import { AuctionLexsDefendantDto } from './auctionLexsDefendantDto';


export interface AuctionLexsNonPledgeAssestDto { 
    assetCollateralSubTypeCode?: number;
    assetCollateralSubTypeDesc?: string;
    assetCollateralTypeCode?: number;
    assetCollateralTypeDesc?: string;
    assetDefendant?: Array<AuctionLexsDefendantDto>;
    assetDescription?: string;
    assetDocumentNo?: string;
    assetId?: number;
    assetObligationBy?: string;
    assetOwners?: Array<AuctionDetailsAssetOwner>;
    assetPlaintiffname?: string;
    assetRedCaseNo?: string;
    ledId?: number;
    ledName?: string;
    litigationCaseId?: number;
}

