/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuctionLexsDefendantDto } from './auctionLexsDefendantDto';


export interface AuctionLexsCollateralDto { 
    collateralId?: number;
    ledId?: string;
    ledName?: string;
    lexsCollateralSubTypeCode?: string;
    lexsCollateralSubTypeDesc?: string;
    lexsCollateralTypeCode?: string;
    lexsCollateralTypeDesc?: string;
    lexsCollateralsDescription?: string;
    lexsDefendant?: Array<AuctionLexsDefendantDto>;
    lexsDocumentNo?: string;
    lexsOwnerFullName?: string;
    lexsPlaintiffName?: string;
    lexsRedCaseNo?: string;
}

