/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeedGroupRecord } from './deedGroupRecord';


export interface AuctionCashierStampDutyResponse { 
    cashierStampDutyId?: number;
    aucRef?: number;
    ledId?: number;
    ledName?: string;
    totalDeedGroup?: number;
    assignedLawyerId?: string;
    assignedLawyerMobileNo?: string;
    branchCode?: string;
    branchName?: string;
    receivedByLawyerId?: string;
    receivedByLawyerMobileNo?: string;
    rejectReason?: string;
    totalAmount?: number;
    status?: string;
    deedGroupRecordList?: Array<DeedGroupRecord>;
    no?: number;
    deedGroupId?: number;
    amount?: number;
    receiveCashierDate?: string;
    feeAmount?: number;
    soldPrice?: number;
    actionFlag?: boolean;
    taskId?: number;
    createdTimeStamp?: string;
    soldDate?: string;
}

