/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionCollateralValidateRequest { 
    deedGroupId?: number;
    deedId?: number;
    validationResult?: string;
    validationNote?: string;
}

