/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionDetailsAssetOwner { 
    cifNo?: string;
    identificationNo?: string;
    title?: string;
    firstName?: string;
    lastName?: string;
    custTypeConst?: string;
}

