/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionLexsDefendantDto { 
    personId?: string;
    personName?: string;
    relation?: string;
    cifNo?: string;
    litigationCaseId?: number;
}

