/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuctionAnnounceExcelDto { 
    no?: string;
    announceDate?: string;
    aucLot?: string;
    aucSet?: string;
    fbidnum?: string;
    redCaseNo?: string;
    defendantName?: string;
    lawCourtName?: string;
    aucStatusName?: string;
}

