/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerProductBS } from './customerProductBS';
import { PaymentSummaryList } from './paymentSummaryList';


export interface BillSummary { 
    amt?: number;
    billDate?: string;
    billID?: number;
    billRef?: string;
    cusRef?: string;
    customerProduct?: CustomerProductBS;
    dueDate?: string;
    expiryDate?: string;
    payeeCode?: string;
    payments?: PaymentSummaryList;
    ref1?: string;
    ref2?: string;
    ref3?: string;
    ref4?: string;
}

