/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CashierChequeDto { 
    amount?: number;
    authorizedUserId?: string;
    chequeStatus?: CashierChequeDto.ChequeStatusEnum;
    chequeType?: CashierChequeDto.ChequeTypeEnum;
    effectiveDate?: string;
    feeAmount?: number;
    glCostCenter?: string;
    id?: number;
    issuedStatus?: string;
    litigationCaseId?: number;
    litigationId?: string;
    objectId?: string;
    objectType?: string;
    outwardBranch?: string;
    payeeName?: string;
    paymentStatus?: string;
    sourceSystem?: string;
    webServiceError?: string;
}
export namespace CashierChequeDto {
    export type ChequeStatusEnum = 'PENDING' | 'SUBMIT' | 'ISSUED' | 'CANCELED' | 'COMPLETE_CANCELLED';
    export const ChequeStatusEnum = {
        Pending: 'PENDING' as ChequeStatusEnum,
        Submit: 'SUBMIT' as ChequeStatusEnum,
        Issued: 'ISSUED' as ChequeStatusEnum,
        Canceled: 'CANCELED' as ChequeStatusEnum,
        CompleteCancelled: 'COMPLETE_CANCELLED' as ChequeStatusEnum
    };
    export type ChequeTypeEnum = 'CHEQUE_AUCTION_ASSET' | 'CHEQUE_DUTY_FEE' | 'CHEQUE_ADDITIONAL_PAYMENT' | 'CHEQUE_TRANSFER_OWNERSHIP' | 'CHEQUE_ADDITIONAL_ANNOUNCE_PAYMENT' | 'CHEQUE_AUCTION_EXPENSE';
    export const ChequeTypeEnum = {
        AuctionAsset: 'CHEQUE_AUCTION_ASSET' as ChequeTypeEnum,
        DutyFee: 'CHEQUE_DUTY_FEE' as ChequeTypeEnum,
        AdditionalPayment: 'CHEQUE_ADDITIONAL_PAYMENT' as ChequeTypeEnum,
        TransferOwnership: 'CHEQUE_TRANSFER_OWNERSHIP' as ChequeTypeEnum,
        AdditionalAnnouncePayment: 'CHEQUE_ADDITIONAL_ANNOUNCE_PAYMENT' as ChequeTypeEnum,
        AuctionExpense: 'CHEQUE_AUCTION_EXPENSE' as ChequeTypeEnum
    };
}


