/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashierChequePaymentDto } from './cashierChequePaymentDto';


export interface CashierChequePaymentRequest { 
    cashierChequePaymentDtoList?: Array<CashierChequePaymentDto>;
}

