/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LitigationCaseDebtInfo } from './litigationCaseDebtInfo';


export interface CloseLitigationRequest { 
    litigationId?: string;
    closeCondition?: CloseLitigationRequest.CloseConditionEnum;
    closeReason?: string;
    litigationCaseDebtInfos?: Array<LitigationCaseDebtInfo>;
    totalDebtAmount?: number;
}
export namespace CloseLitigationRequest {
    export type CloseConditionEnum = 'TRANSFER' | 'CESSATION' | 'WRITE_OFF' | 'DEPT_CLOSED' | 'REFINANCE';
    export const CloseConditionEnum = {
        Transfer: 'TRANSFER' as CloseConditionEnum,
        Cessation: 'CESSATION' as CloseConditionEnum,
        WriteOff: 'WRITE_OFF' as CloseConditionEnum,
        DeptClosed: 'DEPT_CLOSED' as CloseConditionEnum,
        Refinance: 'REFINANCE' as CloseConditionEnum
    };
}


