/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollateralDto { 
    accountGroup?: string;
    accountName?: string;
    accountNo?: string;
    accounts?: Array<string>;
    address1?: string;
    address2?: string;
    address3?: string;
    appraisalDate?: string;
    appraisalPrice?: number;
    appraisalValue?: number;
    areaNgan?: number;
    areaRai?: number;
    areaSqm?: number;
    areaSqrWa?: number;
    bankName?: string;
    blackCaseNo?: string;
    bondNo?: string;
    bondNo2?: string;
    bookNo?: string;
    bookingValue?: number;
    borrower?: string;
    botCode?: string;
    botSubCode?: string;
    buildingFloors?: string;
    buildingName?: string;
    buildingNo?: string;
    buyerName?: string;
    calculatedCollateralStatus?: string;
    cifNo?: string;
    collateralContractStatus?: string;
    collateralId?: string;
    collateralStatusCode?: string;
    collateralStatusDesc?: string;
    collateralSubTypeCode?: string;
    collateralSubTypeDesc?: string;
    collateralTypeCode?: string;
    collateralTypeDesc?: string;
    commodityDesc?: string;
    consignmentAmount?: number;
    consignmentSellerName?: string;
    contractDate?: string;
    contractId?: string;
    contractStatus?: string;
    court?: string;
    currency?: string;
    description?: string;
    district?: string;
    districtCode?: string;
    documentNo?: string;
    dueDate?: string;
    employerName?: string;
    employerType?: string;
    engineNo?: string;
    estimateFreezeAmount?: number;
    expropriate?: string;
    expropriateAmount?: number;
    expropriatePerson?: string;
    externalAssetStatus?: string;
    externalAssetStatusDesc?: string;
    floor?: string;
    foundPropertyProcessType?: string;
    foundPropertyRemark?: string;
    freezeDate?: string;
    insurancePolicyNumber?: string;
    issueDate?: string;
    issuer?: string;
    jobPosition?: string;
    landNo?: string;
    leasePeriod?: number;
    legalStatus?: string;
    legalStatusDesc?: string;
    lendContractNo?: string;
    lendDate?: string;
    lendProduct?: string;
    lendType?: string;
    lender?: string;
    litigationId?: string;
    machineAmount?: number;
    machineName?: string;
    machineNo?: string;
    machineNo2?: string;
    mortgageAmount?: number;
    mortgageeName?: string;
    notTransferOwnershipFromDate?: string;
    notTransferOwnershipToDate?: string;
    notTransferOwnershipWithin?: number;
    obligationStatus?: string;
    obligationType?: string;
    otherIncome?: number;
    otherLitigationId?: string;
    ownerId?: string;
    ownerName?: string;
    parValue?: number;
    pawnAmount?: number;
    pawnName?: string;
    payerOrganization?: string;
    paymentType?: string;
    personId?: string;
    priceValue?: number;
    projectName?: string;
    province?: string;
    provinceCode?: string;
    ravang?: string;
    redCaseNo?: string;
    redeemPeriod?: number;
    registrationNo?: string;
    remainingPeriod?: number;
    remark?: string;
    rentalFee?: number;
    roomNo?: string;
    salary?: number;
    seizureDate?: string;
    seizurePerson?: string;
    seizureRedCaseNo?: string;
    serviceMonth?: number;
    serviceYear?: number;
    sourceSystem?: string;
    subDistrict?: string;
    subdistrictCode?: string;
    surveySection?: string;
    tcg?: boolean;
    totalAppraisalValue?: number;
    typeDescription?: string;
    typeOfContract?: string;
    typeOfContractOrder?: string;
    unit?: string;
    unitAmount?: number;
    updateFlag?: CollateralDto.UpdateFlagEnum;
    vehicleCount?: number;
    vehicleNo?: string;
    weight?: number;
    workOrganization?: string;
}
export namespace CollateralDto {
    export type UpdateFlagEnum = 'A' | 'U' | 'D' | 'A' | 'U' | 'D';
    export const UpdateFlagEnum = {
        A: 'A' as UpdateFlagEnum,
        U: 'U' as UpdateFlagEnum,
        D: 'D' as UpdateFlagEnum,
        A2: 'A' as UpdateFlagEnum,
        U2: 'U' as UpdateFlagEnum,
        D2: 'D' as UpdateFlagEnum
    };
}


