/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollateralDocument { 
    documentName?: string;
    imageSource?: string;
    chronicleId?: string;
    collateralId?: string;
    collateralDocumentNo?: string;
    collateralDetails?: string;
    documentStorageCode?: string;
    documentStorageName?: string;
    receivedDocumentDate?: string;
}

