/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollateralLexsStatusDashboard { 
    /**
     * ไม่ถูกอายัด/ยึด/ขาย
     */
    pledge?: number;
    /**
     * ยึดทรัพย์
     */
    seizured?: number;
    /**
     * อยู่ระหว่างขายทอดตลาด
     */
    onSale?: number;
    /**
     * รอประกาศขายทอดตลาดใหม่
     */
    pendingSale?: number;
    /**
     * ขายทอดตลาดแล้ว
     */
    sold?: number;
}

