/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractDto } from './contractDto';
import { CollateralDto } from './collateralDto';


export interface CollateralInfo { 
    collaterals?: Array<CollateralDto>;
    assets?: Array<CollateralDto>;
    contracts?: Array<ContractDto>;
}

