/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Notification } from './notification';


export interface ConfirmationFormDto { 
    appointmentDate?: string;
    blackCaseNo?: string;
    caseDate?: string;
    confirmImageId?: string;
    confirmImageName?: string;
    confirmRefNo?: string;
    courtFee?: number;
    deliveryFeeForPleadings?: number;
    documentPreparationFee?: number;
    notification?: Notification;
    totalAmount?: number;
}

