/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourtSubVerdict } from './courtSubVerdict';


export interface CourtSubVerdictDto { 
    courtSubVerdictList?: Array<CourtSubVerdict>;
}

