/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourtFeeTransactionDto { 
    transactionName?: string;
    transactionDate?: string;
    courtLevel?: string;
    accountNo?: string;
    initialAmount?: number;
    netAmount?: number;
    courtRefundAmount?: number;
    status?: string;
}

