/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RejectRequest } from './rejectRequest';
import { TransferTransactionDto } from './transferTransactionDto';
import { TransferOrderDto } from './transferOrderDto';


export interface CourtReceiveOrderDto { 
    accountCode?: string;
    cancelReason?: string;
    cancelReasonOther?: string;
    courtName?: string;
    editReason?: string;
    headerFlag?: CourtReceiveOrderDto.HeaderFlagEnum;
    lastAssignDate?: string;
    makerId?: string;
    makerName?: string;
    makerOrgId?: string;
    makerOrgName?: string;
    outboundTransferTransaction?: Array<TransferTransactionDto>;
    payAmount?: number;
    receiveNo?: string;
    receiveSource?: CourtReceiveOrderDto.ReceiveSourceEnum;
    receiveStatus?: CourtReceiveOrderDto.ReceiveStatusEnum;
    receiveStatusName?: string;
    receiveType?: CourtReceiveOrderDto.ReceiveTypeEnum;
    receiveTypeName?: string;
    ref1?: string;
    ref2?: string;
    referenceAmount?: number;
    referenceNo?: string;
    rejectRequest?: RejectRequest;
    sumTotalClearingAmount?: number;
    suspenseAccountDate?: string;
    taskUnprocess?: boolean;
    transferOrders?: Array<TransferOrderDto>;
    unprocessReason?: string;
    updateFlag?: CourtReceiveOrderDto.UpdateFlagEnum;
    washAccountAmount?: number;
    washAccountNo?: string;
}
export namespace CourtReceiveOrderDto {
    export type HeaderFlagEnum = 'DRAFT' | 'SUBMIT' | 'APPROVE' | 'REJECT' | 'CANCEL' | 'DELETE' | 'UPDATE' | 'SUBMIT1' | 'SUBMIT2' | 'SAVE';
    export const HeaderFlagEnum = {
        Draft: 'DRAFT' as HeaderFlagEnum,
        Submit: 'SUBMIT' as HeaderFlagEnum,
        Approve: 'APPROVE' as HeaderFlagEnum,
        Reject: 'REJECT' as HeaderFlagEnum,
        Cancel: 'CANCEL' as HeaderFlagEnum,
        Delete: 'DELETE' as HeaderFlagEnum,
        Update: 'UPDATE' as HeaderFlagEnum,
        Submit1: 'SUBMIT1' as HeaderFlagEnum,
        Submit2: 'SUBMIT2' as HeaderFlagEnum,
        Save: 'SAVE' as HeaderFlagEnum
    };
    export type ReceiveSourceEnum = 'NORMAL' | 'COURT';
    export const ReceiveSourceEnum = {
        Normal: 'NORMAL' as ReceiveSourceEnum,
        Court: 'COURT' as ReceiveSourceEnum
    };
    export type ReceiveStatusEnum = 'DRAFT' | 'PENDING_APPROVE' | 'PENDING_EDIT' | 'PENDING_DOWNLOAD' | 'RECORD_NO_SUCCESS' | 'COMPLETED' | 'COMPLETED_SYSTEM' | 'CANCEL_RECORD' | 'PENDING_NO_SUCCESS';
    export const ReceiveStatusEnum = {
        Draft: 'DRAFT' as ReceiveStatusEnum,
        PendingApprove: 'PENDING_APPROVE' as ReceiveStatusEnum,
        PendingEdit: 'PENDING_EDIT' as ReceiveStatusEnum,
        PendingDownload: 'PENDING_DOWNLOAD' as ReceiveStatusEnum,
        RecordNoSuccess: 'RECORD_NO_SUCCESS' as ReceiveStatusEnum,
        Completed: 'COMPLETED' as ReceiveStatusEnum,
        CompletedSystem: 'COMPLETED_SYSTEM' as ReceiveStatusEnum,
        CancelRecord: 'CANCEL_RECORD' as ReceiveStatusEnum,
        PendingNoSuccess: 'PENDING_NO_SUCCESS' as ReceiveStatusEnum
    };
    export type ReceiveTypeEnum = 'INTER_OFFICE' | 'SUSPENSE' | 'SUSPENSE_COURT' | 'AUTO_CLEARING';
    export const ReceiveTypeEnum = {
        InterOffice: 'INTER_OFFICE' as ReceiveTypeEnum,
        Suspense: 'SUSPENSE' as ReceiveTypeEnum,
        SuspenseCourt: 'SUSPENSE_COURT' as ReceiveTypeEnum,
        AutoClearing: 'AUTO_CLEARING' as ReceiveTypeEnum
    };
    export type UpdateFlagEnum = 'A' | 'U' | 'D';
    export const UpdateFlagEnum = {
        A: 'A' as UpdateFlagEnum,
        U: 'U' as UpdateFlagEnum,
        D: 'D' as UpdateFlagEnum
    };
}


