/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentDto } from './documentDto';
import { CreateAdvanceReceivePayTransferDetail } from './createAdvanceReceivePayTransferDetail';


export interface CreateAdvanceReceivePayTransferInfo { 
    /**
     * คดีหมายเลขดำ
     */
    blackCaseNo?: string;
    /**
     * รายการเลขบัญชีเงินทดลองจ่าย
     */
    createAdvancePayTransferDetail?: Array<CreateAdvanceReceivePayTransferDetail>;
    /**
     * รหัสลูกหนี้
     */
    customerId?: string;
    /**
     * ชื่อลูกหนี้
     */
    customerName?: string;
    /**
     * เอกสารผลการพิพากษา
     */
    documentCourtVerdicts?: Array<DocumentDto>;
    /**
     * รหัสของคดี
     */
    litigationCaseId?: number;
    /**
     * สถานะการดำเนินคดี
     */
    litigationCaseStatus?: string;
    /**
     * LGID
     */
    litigationId?: string;
    /**
     * คดีหมายเลขแดง
     */
    redCaseNo?: string;
    /**
     * รวมสุทธิจำนวนเงินโอน
     */
    sumPayTransfer?: number;
    /**
     * รวมสุทธิจำนวนเงินคงเหลือก่อนโอน
     */
    sumPayTransferBefore?: number;
    /**
     * รวมสุทธิการโอนทดรองจ่าย
     */
    totalNetPayTransfer?: number;
    /**
     * A|U|D
     */
    updateFlag?: CreateAdvanceReceivePayTransferInfo.UpdateFlagEnum;
}
export namespace CreateAdvanceReceivePayTransferInfo {
    export type UpdateFlagEnum = 'A' | 'U' | 'D';
    export const UpdateFlagEnum = {
        A: 'A' as UpdateFlagEnum,
        U: 'U' as UpdateFlagEnum,
        D: 'D' as UpdateFlagEnum
    };
}


