/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerLitigationCaseDto { 
    amdResponseUnitCode?: string;
    amdResponseUnitName?: string;
    amdUserId?: string;
    amdUserName?: string;
    aoUserId?: string;
    aoUserName?: string;
    blackCaseNo?: string;
    customerId?: string;
    customerName?: string;
    defermentStatus?: CustomerLitigationCaseDto.DefermentStatusEnum;
    dpd?: number;
    expireDate?: string;
    flag?: string;
    kbdUserId?: string;
    kbdUserName?: string;
    lawyerId?: string;
    lawyerName?: string;
    lawyerOfficeCode?: string;
    lawyerOfficeName?: string;
    litigationId?: string;
    litigationStatus?: string;
    ownerBranchCode?: string;
    ownerBranchName?: string;
    prescriptionDate?: string;
    redCaseNo?: string;
    responseUnitCode?: string;
    responseUnitName?: string;
}
export namespace CustomerLitigationCaseDto {
    export type DefermentStatusEnum = 'CESSATION' | 'DEFERMENT' | 'NORMAL' | 'DEFERMENT_EXEC_SEIZURE' | 'DEFERMENT_EXEC_SALE' | 'DEFERMENT_EXEC_SEIZURE_SALE';
    export const DefermentStatusEnum = {
        Cessation: 'CESSATION' as DefermentStatusEnum,
        Deferment: 'DEFERMENT' as DefermentStatusEnum,
        Normal: 'NORMAL' as DefermentStatusEnum,
        DefermentExecSeizure: 'DEFERMENT_EXEC_SEIZURE' as DefermentStatusEnum,
        DefermentExecSale: 'DEFERMENT_EXEC_SALE' as DefermentStatusEnum,
        DefermentExecSeizureSale: 'DEFERMENT_EXEC_SEIZURE_SALE' as DefermentStatusEnum
    };
}


