/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeedGroupMatchDetail { 
    fsubbidnum?: string;
    totalDeeds?: number;
    saleTypeDesc?: string;
    reservefund?: string;
    reservefund1?: string;
    assetPrice2?: string;
    assetPrice3?: string;
    assetPrice4?: string;
    assetPrice5?: string;
}

