/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeizureDocumentTemplate } from './seizureDocumentTemplate';
import { RelatedCollateral } from './relatedCollateral';
import { Document } from './document';
import { RejectedReason } from './rejectedReason';


export interface DeedDocument { 
    approveDate?: string;
    approveStatus?: boolean;
    dimHardCopyStatus?: string;
    documentNo?: string;
    documentTemplate?: SeizureDocumentTemplate;
    imageId?: string;
    imageName?: string;
    imageSource?: DeedDocument.ImageSourceEnum;
    rejectedReasons?: Array<RejectedReason>;
    relatedCollateral?: RelatedCollateral;
    sendStatus?: boolean;
    appraisalDate?: string;
    collateralDetails?: string;
    collateralDocNo?: string;
    collateralId?: string;
    collateralSubTypeCode?: string;
    collateralTypeCode?: string;
    collateralsDescription?: string;
    deedId?: number;
    documents?: Array<Document>;
}
export namespace DeedDocument {
    export type ImageSourceEnum = 'LEXS' | 'IMP' | 'DIMS' | 'LG' | 'PN' | 'FCS' | 'TFS' | 'LCS' | 'RLS';
    export const ImageSourceEnum = {
        Lexs: 'LEXS' as ImageSourceEnum,
        Imp: 'IMP' as ImageSourceEnum,
        Dims: 'DIMS' as ImageSourceEnum,
        Lg: 'LG' as ImageSourceEnum,
        Pn: 'PN' as ImageSourceEnum,
        Fcs: 'FCS' as ImageSourceEnum,
        Tfs: 'TFS' as ImageSourceEnum,
        Lcs: 'LCS' as ImageSourceEnum,
        Rls: 'RLS' as ImageSourceEnum
    };
}


