/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Deed { 
    assetTypeDesc?: string;
    collateralDocNo?: string;
    collateralId?: string;
    collateralSubTypeCode?: string;
    collateralTypeCode?: string;
    deedId?: number;
    isDeedInfoValid?: boolean;
    landType?: string;
}

