/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeedGroupRecord { 
    no?: number;
    deedGroupId?: number;
    amount?: number;
    orderPaymentDate?: string;
    feeAmount?: number;
    soldPrice?: number;
    fsubbidnum?: string;
    buyerType?: string;
}

