/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DefermentApprovalHistoryInfo { 
    approveActor?: DefermentApprovalHistoryInfo.ApproveActorEnum;
    approveDate?: string;
    approveResult?: DefermentApprovalHistoryInfo.ApproveResultEnum;
    approverId?: string;
    approverName?: string;
    createdDate?: string;
    defermentId?: string;
    reason?: string;
}
export namespace DefermentApprovalHistoryInfo {
    export type ApproveActorEnum = 'FACTION' | 'GROUP' | 'ORGANIZATION';
    export const ApproveActorEnum = {
        Faction: 'FACTION' as ApproveActorEnum,
        Group: 'GROUP' as ApproveActorEnum,
        Organization: 'ORGANIZATION' as ApproveActorEnum
    };
    export type ApproveResultEnum = 'APPROVE' | 'REJECT' | 'REVISE' | 'AGREE' | 'NOT_AGREE';
    export const ApproveResultEnum = {
        Approve: 'APPROVE' as ApproveResultEnum,
        Reject: 'REJECT' as ApproveResultEnum,
        Revise: 'REVISE' as ApproveResultEnum,
        Agree: 'AGREE' as ApproveResultEnum,
        NotAgree: 'NOT_AGREE' as ApproveResultEnum
    };
}


