/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DimsTicketDocument } from './dimsTicketDocument';


export interface DimsTicketResponse { 
    dimsTicketBarcode?: string;
    documents?: Array<DimsTicketDocument>;
}

