/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentRequest } from './documentRequest';


export interface DocumentInfoRequest { 
    documents?: Array<DocumentRequest>;
    closeTaskId?: number;
}

