/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTemplate } from './documentTemplate';


export interface Document { 
    documentId?: number;
    success?: boolean;
    documentTemplate?: DocumentTemplate;
    documentTemplateId?: string;
    imageId?: string;
    imageName?: string;
    imageSource?: string;
    receiveDate?: string;
    storeOrgCode?: string;
    storeOrgName?: string;
    uploadSessionId?: string;
    uploadTimestamp?: string;
}

