/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageOfDopaTaskDto } from './pageOfDopaTaskDto';


export interface DopaPageResponse { 
    data?: PageOfDopaTaskDto;
    requestTime?: string;
}

