/**
 * KTB Backend for Frontend APIs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorInfo } from './errorInfo';


/**
 * List of Error Information
 */
export interface Errors { 
    /**
     * List of ErrorInfo
     */
    errors: Array<ErrorInfo>;
}

