/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutionReceiptRecord } from './executionReceiptRecord';
import { DocumentDto } from './documentDto';
import { LitigationCasePersonDto } from './litigationCasePersonDto';


export interface ExecutionReceiptDto { 
    headerFlag?: ExecutionReceiptDto.HeaderFlagEnum;
    litigationCaseId?: number;
    persons?: Array<LitigationCasePersonDto>;
    declarationDocuments?: Array<DocumentDto>;
    blackCaseNo?: string;
    redCaseNo?: string;
    executionFeeDate?: string;
    executionReceiptRecords?: Array<ExecutionReceiptRecord>;
}
export namespace ExecutionReceiptDto {
    export type HeaderFlagEnum = 'DRAFT' | 'SUBMIT' | 'APPROVE' | 'REJECT' | 'CANCEL' | 'DELETE' | 'UPDATE' | 'SUBMIT1' | 'SUBMIT2' | 'SAVE';
    export const HeaderFlagEnum = {
        Draft: 'DRAFT' as HeaderFlagEnum,
        Submit: 'SUBMIT' as HeaderFlagEnum,
        Approve: 'APPROVE' as HeaderFlagEnum,
        Reject: 'REJECT' as HeaderFlagEnum,
        Cancel: 'CANCEL' as HeaderFlagEnum,
        Delete: 'DELETE' as HeaderFlagEnum,
        Update: 'UPDATE' as HeaderFlagEnum,
        Submit1: 'SUBMIT1' as HeaderFlagEnum,
        Submit2: 'SUBMIT2' as HeaderFlagEnum,
        Save: 'SAVE' as HeaderFlagEnum
    };
}


