/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentDto } from './documentDto';
import { ExpenseTransactionDto } from './expenseTransactionDto';
import { ExpenseRefundDto } from './expenseRefundDto';


export interface ExpenseDetailDto { 
    accountCode?: string;
    accountName?: string;
    accountNo?: string;
    addressId?: number;
    addressLine?: string;
    approverId?: string;
    businessType?: string;
    cancelDate?: string;
    cancelReason?: string;
    cancelReasonNote?: string;
    cbsErrorReason?: string;
    defaultApproverId?: string;
    districtName?: string;
    downloadDocument?: boolean;
    expenseGroup?: number;
    expenseNo?: string;
    expenseRateId?: string;
    expenseRefundDto?: Array<ExpenseRefundDto>;
    expenseStatusCode?: string;
    expenseStatusName?: string;
    expenseSubTypeCode?: string;
    expenseSubTypeName?: string;
    expenseTransactionDto?: Array<ExpenseTransactionDto>;
    expenseTypeCode?: string;
    expenseTypeName?: string;
    financialApprover2Id?: string;
    financialApproverId?: string;
    financialBossUserId?: string;
    financialMakerId?: string;
    financialNewsReceipt?: DocumentDto;
    klawReceipt?: DocumentDto;
    makerId?: string;
    mergedExpenseTransaction?: ExpenseTransactionDto;
    note?: string;
    paymentMethod?: string;
    paymentMethodName?: string;
    postalCode?: string;
    provinceName?: string;
    receiveDate?: string;
    receiverName?: string;
    referenceExpenseNo?: string;
    rejectReason?: string;
    rejectReasonNote?: string;
    requestKbmReason?: string;
    stepCode?: string;
    stepName?: string;
    stepSubCode?: string;
    stepSubName?: string;
    subDistrictName?: string;
    sumExpenseAmount?: number;
    sumTotalAmount?: number;
    sumVatAmount?: number;
    sumWtAmount?: number;
    taskId?: number;
    taxNo?: string;
    telNo?: string;
    transferDate?: string;
    type?: string;
    vatRate?: number;
    whtRate?: number;
}

