/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseDashboard { 
    /**
     * จำนวนรายการเบิกงานที่รออนุมัติการจ่ายเงินโดย KTB
     */
    pendingApproval?: number;
    /**
     * จำนวนรายการเบิกงานที่รออัปโหลดใบเสร็จ
     */
    pendingReceiptUpload?: number;
    /**
     * จำนวนรายการเบิกงานที่รออัปโหลดใบเสร็จสำหรับรายการเบิกเงินอัตโนมัติ
     */
    pendingReceiptUploadAuto?: number;
    /**
     * จำนวนรายการเบิกงานที่รอตรวจสอบโดย KLAW
     */
    pendingVerification?: number;
    /**
     * จำนวนรายการเบิกเงินที่รอตรวจสอบโดย KTB
     */
    pendingVerificationAuto?: number;
    /**
     * จำนวนรายการเบิกเงินอัโนมัติที่รอตรวจสอบโดย KLAW
     */
    pendingVerificationKlawAuto?: number;
}

