/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollateralGroup } from './collateralGroup';


export interface ExternalPaymentTrackingResponse { 
    externalPaymentTrackingId?: number;
    aucRef?: number;
    aucRound?: number;
    trackingRound?: number;
    bidDate?: string;
    aucLedSeq?: number;
    aucBiddingId?: number;
    onSiteLawyerId?: string;
    status?: string;
    statusName?: string;
    ledName?: string;
    collateralGroups?: Array<CollateralGroup>;
}

