/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialTransactionSummaryDashboard } from './financialTransactionSummaryDashboard';


/**
 * ข้อมูลการเงินระดับ LG ID
 */
export interface FinancialCustomerSummaryDetailDto { 
    /**
     * LG ID
     */
    litigationId?: string;
    litigationTransactionDashboard?: FinancialTransactionSummaryDashboard;
}

