/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialSummaryTransactionDto } from './financialSummaryTransactionDto';


export interface FinancialTransactionSummaryDashboard { 
    /**
     * ข้อมูลการเงิน
     */
    financialSummaryTransactionList?: Array<FinancialSummaryTransactionDto>;
    /**
     * ผลรวมปรับปรุงรายการ (Axx)
     */
    sumAdjustAmount?: number;
    /**
     * ผลรวมจำนวนเงิน
     */
    sumAmount?: number;
    /**
     * ผลรวมยกเลิกจ่าย (Cxx)
     */
    sumCancelAmount?: number;
    /**
     * ผลรวมรายจ่าย (Exx)
     */
    sumExpenseAmount?: number;
    /**
     * ผลรวมตัดเดิม (G10)
     */
    sumG10AdvanceAmount?: number;
    /**
     * ผลรวมเป็นพับ (G12)
     */
    sumG12AdvanceAmount?: number;
    /**
     * ผลรวมลด/ยกเว้น (G13)
     */
    sumG13AdvanceAmount?: number;
    /**
     * ผลรวมเลิกตาม (G14)
     */
    sumG14AdvanceAmount?: number;
    /**
     * ผลรวมติดตาม (G15)
     */
    sumG15AdvanceAmount?: number;
    /**
     * ผลรวมคงค้าง
     */
    sumOutstandingBalanceAmount?: number;
    /**
     * ผลรวมรายรับ (Rxx)
     */
    sumReceiveAmount?: number;
    /**
     * ผลรวม
     */
    sumTotalAmount?: number;
}

