/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InquiryCollateralResponse { 
    billNo?: string;
    collateralId?: string;
    collateralTypeCode?: string;
    collateralTypeDesc?: string;
    collateralSubTypeCode?: string;
    collateralSubTypeDesc?: string;
    documentNo?: string;
    description?: string;
    selected?: boolean;
    ownerName?: string;
    collateralCmsStatus?: string;
    collateralCaseLexStatus?: string;
    litigationIds?: string;
    totalAppraisalAmount?: number;
}

