/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InquiryLitigationDto { 
    blackCaseNo?: string;
    customerId?: string;
    customerName?: string;
    customerStatus?: string;
    customerStatusName?: string;
    litigationCaseId?: number;
    litigationClosed?: boolean;
    litigationId?: string;
    redCaseNo?: string;
}

