/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeedGroupBiddingCollateral } from './deedGroupBiddingCollateral';


export interface InquiryBiddingCollateralResponse { 
    aucLedSeq?: string;
    aucRef?: string;
    deedGroups?: Array<DeedGroupBiddingCollateral>;
    lawCourtId?: string;
    lawCourtName?: string;
    ledId?: string;
    ledName?: string;
    saleChannel?: string;
}

