/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InterestSummary { 
    accrualInterest?: number;
    currentRate?: number;
    fixedRateDifferential?: string;
    interestIndex?: string;
    interestSpread?: string;
    lastAmountAccrued?: number;
    lateCharge?: number;
    miscCharge?: number;
    relatedDeposit?: string;
}

