/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LatestResolutionInfoResponse { 
    resolution?: string;
    saletypedesc?: string;
    minPrice?: number;
    maxPrice?: number;
    genCbsAppval?: number;
    effectiveDateTo?: string;
    chronicleId?: string;
}

