/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LedInfoDto } from './ledInfoDto';


export interface LedInfoResponse { 
    ledInfo?: Array<LedInfoDto>;
}

