/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KlawConfigs } from './klawConfigs';
import { ResponseUnitRequest } from './responseUnitRequest';
import { LexsConfig } from './lexsConfig';


export interface LexsConfigRequest { 
    configs?: Array<LexsConfig>;
    klawConfigs?: Array<KlawConfigs>;
    responseUnitRequest?: Array<ResponseUnitRequest>;
}

