/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LexsUserRequest { 
    authorityCode?: string;
    dataScopeCode?: string;
    factionCode?: string;
    groupCode?: string;
    lawyerCode?: string;
    levelCode?: string;
    mobileNumber?: string;
    organizationCode?: string;
    roleCode?: string;
    subRoleCode?: string;
    supervisorId?: string;
    teamCode?: string;
    updateFlag?: string;
    userId?: string;
}

