/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LitigationCaseDto } from './litigationCaseDto';


export interface LitigationCaseGroupDto { 
    /**
     * Group keys are: civil_court_black_case_no or id
     */
    caseGroupKey?: string;
    /**
     * คดีความที่
     */
    caseGroupNo?: string;
    cases?: Array<LitigationCaseDto>;
    /**
     * Group of คดีแพ่ง
     */
    civilCourtBlackCaseNo?: string;
    /**
     * รหัสทนายความ
     */
    lawyerId?: string;
    /**
     * ชื่อทนายความ
     */
    lawyerName?: string;
    /**
     * รหัสสำนักงานทนายความ
     */
    lawyerOfficeCode?: string;
    /**
     * ชื่อสำนักงานทนายความ
     */
    lawyerOfficeName?: string;
}

