/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationCaseAllegationDto { 
    litigationCaseId?: number;
    /**
     * รหัส
     */
    code?: string;
    /**
     * ชื่อข้อหาฐานความผิด
     */
    name?: string;
}

