/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemoDto } from './memoDto';


export interface LitigationMemoInfo { 
    actionButton?: boolean;
    memoList?: Array<MemoDto>;
}

