/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationSearchConditionRequest { 
    legalStatus?: string;
    lawyer?: string;
    responseUnit?: string;
    amdUnit?: string;
    searchString?: string;
    customerId?: string;
    litigationId?: string;
    customerName?: string;
    customerSurname?: string;
    citizenId?: string;
    blackCaseId?: string;
    redCaseId?: string;
    caseStatus?: string;
    litigationCloseStatus?: string;
    searchScope?: string;
    customerStatus?: string;
    orgCode?: string;
    loanType?: Array<string>;
    accountNo?: string;
    billNo?: string;
    kbdId?: string;
    debtor?: string;
    tamcFlag?: string;
    samFlag?: string;
    writeOffStatus?: string;
    debtTransferTo?: Array<string>;
    caseCreator?: string;
    court?: string;
    ownerId?: string;
    roomNo?: string;
    /**
     * BASIC, ADVANCE, LIST
     */
    searchMode: LitigationSearchConditionRequest.SearchModeEnum;
    /**
     * USER, TEAM, ORG, CLOSED, DASHBOARD
     */
    tab: LitigationSearchConditionRequest.TabEnum;
    /**
     * ALL, STATUS_APPROVE, STATUS_NOTICE, STATUS_IN_PROGRESS, STATUS_DEFER, STATUS_ADJUDICATION, STATUS_SEIZURED, STATUS_WRIT_OF_EXECUTION, STATUS_AUCTION, STATUS_DEFER_EXECUTION, STATUS_ASSET_INVESTIGATION
     */
    statusDashboard?: string;
    /**
     * ALL_DEFERMENT, DEFER_NONE_NOTICE, DEFER_NOTICE
     */
    deferDashboard?: string;
    /**
     * ALL_DEFERMENT_EXEC, DEFER_EXEC_WRIT_OF_EXEC, DEFER_EXEC_SEIZURE, DEFER_EXEC_AUCTION, DEFER_EXEC_OTHER
     */
    deferExecDashboard?: string;
}
export namespace LitigationSearchConditionRequest {
    export type SearchModeEnum = 'BASIC' | 'ADVANCE' | 'LIST';
    export const SearchModeEnum = {
        Basic: 'BASIC' as SearchModeEnum,
        Advance: 'ADVANCE' as SearchModeEnum,
        List: 'LIST' as SearchModeEnum
    };
    export type TabEnum = 'USER' | 'TEAM' | 'ORG' | 'CLOSED' | 'DASHBOARD' | 'PREFERENCE' | 'NOT_PREFERENCE' | 'ALL';
    export const TabEnum = {
        User: 'USER' as TabEnum,
        Team: 'TEAM' as TabEnum,
        Org: 'ORG' as TabEnum,
        Closed: 'CLOSED' as TabEnum,
        Dashboard: 'DASHBOARD' as TabEnum,
        Preference: 'PREFERENCE' as TabEnum,
        NotPreference: 'NOT_PREFERENCE' as TabEnum,
        All: 'ALL' as TabEnum
    };
}


