/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationDefermentExecDashboard { 
    /**
     * อยู่ระหว่างขายทอดตลาด
     */
    deferExecAuction?: number;
    /**
     * อื่นๆ
     */
    deferExecOther?: number;
    /**
     * อยู่ระหว่างยึดทรัพย์
     */
    deferExecSeizure?: number;
    /**
     * ก่อนออกหมายบังคับคดี
     */
    deferExecWritOfExec?: number;
    /**
     * เลขที่กฎหมายที่ไม่มีการชะลอบังคับคดี
     */
    noneDefermentExec?: number;
}

