/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationStatusDashboardExcelDto { 
    accountNoList?: string;
    amdResponseUnit?: string;
    amdResponseUserName?: string;
    customerId?: string;
    customerName?: string;
    dpd?: string;
    litigationId?: string;
    litigationStatusDesc?: string;
    marketCodeList?: string;
    maxCFinal?: string;
    maxStageAccount?: string;
    prescriptionDate?: string;
    responseUnit?: string;
    responseUserName?: string;
    runningNumber?: number;
}

