/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationTransactionDto { 
    blackCaseNo?: string;
    branchCode?: string;
    branchName?: string;
    court?: string;
    customerName?: string;
    litigationCaseId?: number;
    litigationId?: string;
    payAmount?: number;
    redCaseNo?: string;
    refundAmount?: number;
    responseBranchCode?: string;
    responseBranchName?: string;
}

