/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LitigationCaseAccount { 
    accountId?: string;
    lateCharge?: number;
    lateChargeAmount?: number;
    litigationCaseId?: number;
    outstandingBalance?: number;
    totalAmount?: number;
    verdictInterestStartDate?: string;
    verdictLateCharge?: number;
    verdictLateChargeAmount?: number;
    verdictOutstandingBalance?: number;
    verdictTotalAmount?: number;
}

