/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonPledgePropertiesInfoProcessingDoc } from './nonPledgePropertiesInfoProcessingDoc';
import { SeizureInfo } from './seizureInfo';


export interface LitigationCaseInfo { 
    litigationCaseId?: number;
    courtBlackCaseNo?: string;
    courtRedCaseNo?: string;
    litigationCaseCollateralsCount?: number;
    litigationCaseAssetsCount?: number;
    processingDocument?: Array<NonPledgePropertiesInfoProcessingDoc>;
    seizures?: Array<SeizureInfo>;
}

