/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LitigationCaseMainDto } from './litigationCaseMainDto';


export interface LitigationDto { 
    litigationId?: string;
    litigationCaseId?: string;
    customerId?: string;
    customerName?: string;
    blackCaseNo?: string;
    redCaseNo?: string;
    prescriptionDate?: string;
    dpd?: number;
    lawyerOfficeCode?: string;
    lawyerOfficeName?: string;
    lawyerId?: string;
    lawyerName?: string;
    ownerBranchCode?: string;
    ownerBranchName?: string;
    amdResponseUnitCode?: string;
    amdResponseUnitName?: string;
    kbdUserId?: string;
    amdUserId?: string;
    litigationStatus?: string;
    litigationStatusDesc?: string;
    defermentStatus?: LitigationDto.DefermentStatusEnum;
    flag?: string;
    aoUserId?: string;
    aoUserName?: string;
    kbdUserName?: string;
    defermentEndDate?: string;
    defermentBy?: string;
    responseUnitCode?: string;
    responseUnitName?: string;
    responseUserId?: string;
    responseUserName?: string;
    amdResponseUserId?: string;
    amdResponseUserName?: string;
    accountNoCount?: number;
    accountNoList?: string;
    marketCodeList?: string;
    accountMarketCodeList?: string;
    maxCFinal?: string;
    maxStageAccount?: string;
    displayCFinalAndStage?: string;
    actionFlag?: boolean;
    displayResponseUnit?: string;
    displayAmdResponseUnit?: string;
    totalCount?: number;
    litigationCaseMainDtoList?: Array<LitigationCaseMainDto>;
}
export namespace LitigationDto {
    export type DefermentStatusEnum = 'CESSATION' | 'DEFERMENT' | 'NORMAL' | 'DEFERMENT_EXEC_SEIZURE' | 'DEFERMENT_EXEC_SALE' | 'DEFERMENT_EXEC_SEIZURE_SALE';
    export const DefermentStatusEnum = {
        Cessation: 'CESSATION' as DefermentStatusEnum,
        Deferment: 'DEFERMENT' as DefermentStatusEnum,
        Normal: 'NORMAL' as DefermentStatusEnum,
        DefermentExecSeizure: 'DEFERMENT_EXEC_SEIZURE' as DefermentStatusEnum,
        DefermentExecSale: 'DEFERMENT_EXEC_SALE' as DefermentStatusEnum,
        DefermentExecSeizureSale: 'DEFERMENT_EXEC_SEIZURE_SALE' as DefermentStatusEnum
    };
}


