/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollateralAuctionInfo } from './collateralAuctionInfo';
import { DefermentCollateralDeedDto } from './defermentCollateralDeedDto';


export interface LitigationCollateralDeedGroupDto { 
    aucLot?: string;
    aucRef?: number;
    auctionInfos?: Array<CollateralAuctionInfo>;
    blackCaseNo?: string;
    collaterals?: Array<DefermentCollateralDeedDto>;
    deedGroupId?: number;
    enabled?: boolean;
    fsubbidnum?: string;
    ledId?: number;
    ledName?: string;
    litigationCaseId?: number;
    litigationId?: string;
    redCaseNo?: string;
    saletypedesc?: string;
    totalDeeds?: number;
}

