/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MasAppointmentInfoResponse { 
    appointmentId?: number;
    appointmentRound?: number;
    aucRef?: number;
    cifNo?: string;
    conveyanceStatus?: string;
    conveyanceStatusTimestamp?: string;
    conveyancingAppointmentStatus?: MasAppointmentInfoResponse.ConveyancingAppointmentStatusEnum;
    conveyancingAppointmentStatusTimestamp?: string;
    customerName?: string;
    deedGroupId?: number;
    fbidnum?: string;
    fsubbidnum?: string;
    identificationNo?: string;
    isLatest?: boolean;
    ledName?: string;
    masAppointDate?: string;
    masAppointPeriod?: string;
    masAppointUserId?: string;
    masAppointUserName?: string;
    masBranchId?: string;
    masBranchName?: string;
    masCallbackTimestamp?: string;
    masCostCenterId?: string;
    masCostCenterName?: string;
    masLocationId?: string;
    masLocationName?: string;
    masPostponeReason?: string;
    masReferenceNum?: string;
}
export namespace MasAppointmentInfoResponse {
    export type ConveyancingAppointmentStatusEnum = 'SUBMIT_MAS' | 'POSTPONED' | 'APPOINTED' | 'SUCCESS';
    export const ConveyancingAppointmentStatusEnum = {
        SubmitMas: 'SUBMIT_MAS' as ConveyancingAppointmentStatusEnum,
        Postponed: 'POSTPONED' as ConveyancingAppointmentStatusEnum,
        Appointed: 'APPOINTED' as ConveyancingAppointmentStatusEnum,
        Success: 'SUCCESS' as ConveyancingAppointmentStatusEnum
    };
}


