/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAttribute } from './userAttribute';


export interface MeLexsUserDto { 
    attributes?: Array<UserAttribute>;
    authorityCode?: string;
    authorityName?: string;
    category?: string;
    dataScopeCode?: string;
    disable?: boolean;
    email?: string;
    factionCode?: string;
    factionName?: string;
    groupCode?: string;
    groupName?: string;
    lastLogin?: string;
    lawyerCode?: string;
    levelCode?: string;
    levelName?: string;
    mobileNumber?: string;
    name?: string;
    nameEng?: string;
    organizationCode?: string;
    organizationName?: string;
    originalOrganizationCode?: string;
    originalOrganizationName?: string;
    permissions?: Array<string>;
    position?: string;
    roleCode?: string;
    roleName?: string;
    status?: string;
    subRoleCode?: string;
    subRoleName?: string;
    supervisorEmail?: string;
    supervisorId?: string;
    supervisorMobileNumber?: string;
    supervisorName?: string;
    surname?: string;
    surnameEng?: string;
    teamCode?: string;
    teamName?: string;
    title?: string;
    titleEng?: string;
    userId?: string;
}

