/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrganizationMap { 
    authorityCode?: string;
    authorityName?: string;
    factionCode?: string;
    factionName?: string;
    groupCode?: string;
    groupName?: string;
    id?: number;
    organizationCode?: string;
    organizationName?: string;
    roleCode?: string;
    teamCode?: string;
    teamName?: string;
}

