/**
 * KTB Backend for Frontend APIs.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LitigationDto } from './litigationDto';
import { Pageable } from './pageable';
import { Sort } from './sort';


export interface PageOfLitigationDto { 
    content?: Array<LitigationDto>;
    empty?: boolean;
    first?: boolean;
    last?: boolean;
    number?: number;
    numberOfElements?: number;
    pageable?: Pageable;
    size?: number;
    sort?: Sort;
    totalElements?: number;
    totalPages?: number;
}

