/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonAddressDto { 
    addressLine?: string;
    addressType?: string;
    countryCode?: string;
    districtCode?: string;
    districtName?: string;
    lastUpdate?: string;
    personId?: string;
    postalCode?: string;
    provinceCode?: string;
    provinceName?: string;
    sourceSystem?: string;
    subdistrictCode?: string;
    subdistrictName?: string;
}

