/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonAddressDto } from './personAddressDto';
import { PersonBankruptcyDto } from './personBankruptcyDto';


export interface PersonDto { 
    address?: Array<PersonAddressDto>;
    addressChanged?: boolean;
    allRelations?: Array<PersonDto.AllRelationsEnum>;
    bankruptcy?: Array<PersonBankruptcyDto>;
    birthDate?: string;
    deathCertDt?: string;
    deathCertFlag?: boolean;
    dopaDbdName?: string;
    firstName?: string;
    haveHeir?: boolean;
    identificationNo?: string;
    lastName?: string;
    lastUpdate?: string;
    name?: string;
    personId?: string;
    personStatus?: PersonDto.PersonStatusEnum;
    personType?: PersonDto.PersonTypeEnum;
    referencePersonId?: string;
    relation?: PersonDto.RelationEnum;
    relationContractStatus?: string;
    relationList?: Array<PersonDto.RelationListEnum>;
    sourceSystem?: string;
    title?: string;
    updateFlag?: PersonDto.UpdateFlagEnum;
}
export namespace PersonDto {
    export type AllRelationsEnum = 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT' | 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT';
    export const AllRelationsEnum = {
        MainBorrower: 'MAIN_BORROWER' as AllRelationsEnum,
        CoBorrower: 'CO_BORROWER' as AllRelationsEnum,
        Guarantor: 'GUARANTOR' as AllRelationsEnum,
        CollateralOwner: 'COLLATERAL_OWNER' as AllRelationsEnum,
        MainBorrowerTrustee: 'MAIN_BORROWER_TRUSTEE' as AllRelationsEnum,
        CoBorrowerTrustee: 'CO_BORROWER_TRUSTEE' as AllRelationsEnum,
        GuarantorTrustee: 'GUARANTOR_TRUSTEE' as AllRelationsEnum,
        MainBorrowerHeir: 'MAIN_BORROWER_HEIR' as AllRelationsEnum,
        CoBorrowerHeir: 'CO_BORROWER_HEIR' as AllRelationsEnum,
        GuarantorHeir: 'GUARANTOR_HEIR' as AllRelationsEnum,
        StandInPayer: 'STAND_IN_PAYER' as AllRelationsEnum,
        DebtAcceptor: 'DEBT_ACCEPTOR' as AllRelationsEnum,
        DebtAcceptSigner: 'DEBT_ACCEPT_SIGNER' as AllRelationsEnum,
        CoDefendant: 'CO_DEFENDANT' as AllRelationsEnum,
        MainBorrower2: 'MAIN_BORROWER' as AllRelationsEnum,
        CoBorrower2: 'CO_BORROWER' as AllRelationsEnum,
        Guarantor2: 'GUARANTOR' as AllRelationsEnum,
        CollateralOwner2: 'COLLATERAL_OWNER' as AllRelationsEnum,
        MainBorrowerTrustee2: 'MAIN_BORROWER_TRUSTEE' as AllRelationsEnum,
        CoBorrowerTrustee2: 'CO_BORROWER_TRUSTEE' as AllRelationsEnum,
        GuarantorTrustee2: 'GUARANTOR_TRUSTEE' as AllRelationsEnum,
        MainBorrowerHeir2: 'MAIN_BORROWER_HEIR' as AllRelationsEnum,
        CoBorrowerHeir2: 'CO_BORROWER_HEIR' as AllRelationsEnum,
        GuarantorHeir2: 'GUARANTOR_HEIR' as AllRelationsEnum,
        StandInPayer2: 'STAND_IN_PAYER' as AllRelationsEnum,
        DebtAcceptor2: 'DEBT_ACCEPTOR' as AllRelationsEnum,
        DebtAcceptSigner2: 'DEBT_ACCEPT_SIGNER' as AllRelationsEnum,
        CoDefendant2: 'CO_DEFENDANT' as AllRelationsEnum
    };
    export type PersonStatusEnum = 'ALIVE' | 'DEATH' | 'OPEN' | 'CLOSE' | 'ALIVE' | 'DEATH' | 'OPEN' | 'CLOSE';
    export const PersonStatusEnum = {
        Alive: 'ALIVE' as PersonStatusEnum,
        Death: 'DEATH' as PersonStatusEnum,
        Open: 'OPEN' as PersonStatusEnum,
        Close: 'CLOSE' as PersonStatusEnum,
        Alive2: 'ALIVE' as PersonStatusEnum,
        Death2: 'DEATH' as PersonStatusEnum,
        Open2: 'OPEN' as PersonStatusEnum,
        Close2: 'CLOSE' as PersonStatusEnum
    };
    export type PersonTypeEnum = 'INDIVIDUAL' | 'JURISTIC' | 'INDIVIDUAL' | 'JURISTIC';
    export const PersonTypeEnum = {
        Individual: 'INDIVIDUAL' as PersonTypeEnum,
        Juristic: 'JURISTIC' as PersonTypeEnum,
        Individual2: 'INDIVIDUAL' as PersonTypeEnum,
        Juristic2: 'JURISTIC' as PersonTypeEnum
    };
    export type RelationEnum = 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT' | 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT';
    export const RelationEnum = {
        MainBorrower: 'MAIN_BORROWER' as RelationEnum,
        CoBorrower: 'CO_BORROWER' as RelationEnum,
        Guarantor: 'GUARANTOR' as RelationEnum,
        CollateralOwner: 'COLLATERAL_OWNER' as RelationEnum,
        MainBorrowerTrustee: 'MAIN_BORROWER_TRUSTEE' as RelationEnum,
        CoBorrowerTrustee: 'CO_BORROWER_TRUSTEE' as RelationEnum,
        GuarantorTrustee: 'GUARANTOR_TRUSTEE' as RelationEnum,
        MainBorrowerHeir: 'MAIN_BORROWER_HEIR' as RelationEnum,
        CoBorrowerHeir: 'CO_BORROWER_HEIR' as RelationEnum,
        GuarantorHeir: 'GUARANTOR_HEIR' as RelationEnum,
        StandInPayer: 'STAND_IN_PAYER' as RelationEnum,
        DebtAcceptor: 'DEBT_ACCEPTOR' as RelationEnum,
        DebtAcceptSigner: 'DEBT_ACCEPT_SIGNER' as RelationEnum,
        CoDefendant: 'CO_DEFENDANT' as RelationEnum,
        MainBorrower2: 'MAIN_BORROWER' as RelationEnum,
        CoBorrower2: 'CO_BORROWER' as RelationEnum,
        Guarantor2: 'GUARANTOR' as RelationEnum,
        CollateralOwner2: 'COLLATERAL_OWNER' as RelationEnum,
        MainBorrowerTrustee2: 'MAIN_BORROWER_TRUSTEE' as RelationEnum,
        CoBorrowerTrustee2: 'CO_BORROWER_TRUSTEE' as RelationEnum,
        GuarantorTrustee2: 'GUARANTOR_TRUSTEE' as RelationEnum,
        MainBorrowerHeir2: 'MAIN_BORROWER_HEIR' as RelationEnum,
        CoBorrowerHeir2: 'CO_BORROWER_HEIR' as RelationEnum,
        GuarantorHeir2: 'GUARANTOR_HEIR' as RelationEnum,
        StandInPayer2: 'STAND_IN_PAYER' as RelationEnum,
        DebtAcceptor2: 'DEBT_ACCEPTOR' as RelationEnum,
        DebtAcceptSigner2: 'DEBT_ACCEPT_SIGNER' as RelationEnum,
        CoDefendant2: 'CO_DEFENDANT' as RelationEnum
    };
    export type RelationListEnum = 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT' | 'MAIN_BORROWER' | 'CO_BORROWER' | 'GUARANTOR' | 'COLLATERAL_OWNER' | 'MAIN_BORROWER_TRUSTEE' | 'CO_BORROWER_TRUSTEE' | 'GUARANTOR_TRUSTEE' | 'MAIN_BORROWER_HEIR' | 'CO_BORROWER_HEIR' | 'GUARANTOR_HEIR' | 'STAND_IN_PAYER' | 'DEBT_ACCEPTOR' | 'DEBT_ACCEPT_SIGNER' | 'CO_DEFENDANT';
    export const RelationListEnum = {
        MainBorrower: 'MAIN_BORROWER' as RelationListEnum,
        CoBorrower: 'CO_BORROWER' as RelationListEnum,
        Guarantor: 'GUARANTOR' as RelationListEnum,
        CollateralOwner: 'COLLATERAL_OWNER' as RelationListEnum,
        MainBorrowerTrustee: 'MAIN_BORROWER_TRUSTEE' as RelationListEnum,
        CoBorrowerTrustee: 'CO_BORROWER_TRUSTEE' as RelationListEnum,
        GuarantorTrustee: 'GUARANTOR_TRUSTEE' as RelationListEnum,
        MainBorrowerHeir: 'MAIN_BORROWER_HEIR' as RelationListEnum,
        CoBorrowerHeir: 'CO_BORROWER_HEIR' as RelationListEnum,
        GuarantorHeir: 'GUARANTOR_HEIR' as RelationListEnum,
        StandInPayer: 'STAND_IN_PAYER' as RelationListEnum,
        DebtAcceptor: 'DEBT_ACCEPTOR' as RelationListEnum,
        DebtAcceptSigner: 'DEBT_ACCEPT_SIGNER' as RelationListEnum,
        CoDefendant: 'CO_DEFENDANT' as RelationListEnum,
        MainBorrower2: 'MAIN_BORROWER' as RelationListEnum,
        CoBorrower2: 'CO_BORROWER' as RelationListEnum,
        Guarantor2: 'GUARANTOR' as RelationListEnum,
        CollateralOwner2: 'COLLATERAL_OWNER' as RelationListEnum,
        MainBorrowerTrustee2: 'MAIN_BORROWER_TRUSTEE' as RelationListEnum,
        CoBorrowerTrustee2: 'CO_BORROWER_TRUSTEE' as RelationListEnum,
        GuarantorTrustee2: 'GUARANTOR_TRUSTEE' as RelationListEnum,
        MainBorrowerHeir2: 'MAIN_BORROWER_HEIR' as RelationListEnum,
        CoBorrowerHeir2: 'CO_BORROWER_HEIR' as RelationListEnum,
        GuarantorHeir2: 'GUARANTOR_HEIR' as RelationListEnum,
        StandInPayer2: 'STAND_IN_PAYER' as RelationListEnum,
        DebtAcceptor2: 'DEBT_ACCEPTOR' as RelationListEnum,
        DebtAcceptSigner2: 'DEBT_ACCEPT_SIGNER' as RelationListEnum,
        CoDefendant2: 'CO_DEFENDANT' as RelationListEnum
    };
    export type UpdateFlagEnum = 'A' | 'U' | 'D' | 'A' | 'U' | 'D';
    export const UpdateFlagEnum = {
        A: 'A' as UpdateFlagEnum,
        U: 'U' as UpdateFlagEnum,
        D: 'D' as UpdateFlagEnum,
        A2: 'A' as UpdateFlagEnum,
        U2: 'U' as UpdateFlagEnum,
        D2: 'D' as UpdateFlagEnum
    };
}


