/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CasePersonDto } from './casePersonDto';
import { PersonDto } from './personDto';


export interface PersonInfo { 
    persons?: Array<PersonDto>;
    additionalPersons?: Array<PersonDto>;
    casePerson?: CasePersonDto;
}

