/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonAddressRequest { 
    litigationId?: string;
    personId?: string;
    addressLine?: string;
    subdistrictCode?: string;
    subdistrictName?: string;
    districtCode?: string;
    districtName?: string;
    provinceCode?: string;
    provinceName?: string;
}

