/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List รายการบอกกล่าว
 */
export interface PostalDto { 
    /**
     * Notice ID
     */
    noticeId?: number;
    /**
     * เลขอ้างอิงที่ได้จากการแนบเอกสาร (ใบเหลือง)
     */
    postalImageId?: string;
    /**
     * ประเภทที่อยู่ REGISTRATION(ที่อยู่ตามทะเบียน), CONTRACT(ที่อยู่ตามสัญญา), RECEIVERSHIP(พิทักษ์ทรัพย์)
     */
    addressType?: PostalDto.AddressTypeEnum;
    /**
     * หมายเลขหนังสือบอกกล่าว
     */
    noticeNo?: string;
    updateFlag?: PostalDto.UpdateFlagEnum;
}
export namespace PostalDto {
    export type AddressTypeEnum = 'REGISTRATION' | 'CONTRACT' | 'RECEIVERSHIP';
    export const AddressTypeEnum = {
        Registration: 'REGISTRATION' as AddressTypeEnum,
        Contract: 'CONTRACT' as AddressTypeEnum,
        Receivership: 'RECEIVERSHIP' as AddressTypeEnum
    };
    export type UpdateFlagEnum = 'A' | 'U' | 'D';
    export const UpdateFlagEnum = {
        A: 'A' as UpdateFlagEnum,
        U: 'U' as UpdateFlagEnum,
        D: 'D' as UpdateFlagEnum
    };
}


