/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyBS } from './companyBS';
import { ProdChannel } from './prodChannel';


export interface ProductBS { 
    channels?: Array<ProdChannel>;
    company?: CompanyBS;
    nameEn?: string;
    nameTh?: string;
    papiFlg?: string;
    payeeCode?: string;
    prodCode?: string;
    prodID?: number;
    typList?: string;
}

