/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RateDetermination { 
    asOfDate?: string;
    index?: string;
    interestChangeFrequency?: string;
    interestIndex?: string;
    interestRate?: number;
    interestSpread?: number;
    lastInterestRateChangeDate?: string;
    nextInterestRateChangeDate?: string;
    originalIndexValue?: number;
    originalInterestRate?: number;
    rate?: number;
    rateChangeMthod?: string;
    spread?: number;
}

