/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiveAccountCode { 
    code?: string;
    caption?: string;
    receiveType?: ReceiveAccountCode.ReceiveTypeEnum;
}
export namespace ReceiveAccountCode {
    export type ReceiveTypeEnum = 'INTER_OFFICE' | 'SUSPENSE' | 'SUSPENSE_COURT' | 'AUTO_CLEARING';
    export const ReceiveTypeEnum = {
        InterOffice: 'INTER_OFFICE' as ReceiveTypeEnum,
        Suspense: 'SUSPENSE' as ReceiveTypeEnum,
        SuspenseCourt: 'SUSPENSE_COURT' as ReceiveTypeEnum,
        AutoClearing: 'AUTO_CLEARING' as ReceiveTypeEnum
    };
}


