/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleLevelMap { 
    advanceReceiveFinishedScope?: string;
    advanceReceiveOrgScope?: string;
    customerOrgScope?: string;
    customerTeamScope?: string;
    customerUserScope?: string;
    dashboardScope?: string;
    expenseFinishedScope?: string;
    expenseOrgScope?: string;
    expenseTeamScope?: string;
    expenseUserScope?: string;
    levelCode?: string;
    levelName?: string;
    litigationOrgScope?: string;
    litigationTeamScope?: string;
    litigationUserScope?: string;
    receiveFinishedScope?: string;
    receiveOrgScope?: string;
    receiveTeamScope?: string;
    receiveUserScope?: string;
    roleCode?: string;
    taskOrgScope?: string;
    taskPoolScope?: string;
    taskTeamScope?: string;
    taskUserScope?: string;
}

