/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefermentItem } from './defermentItem';


export interface SaveDefermentRequest { 
    customerId: string;
    defermentType: SaveDefermentRequest.DefermentTypeEnum;
    headerFlag?: SaveDefermentRequest.HeaderFlagEnum;
    taskId?: number;
    defermentItem?: DefermentItem;
}
export namespace SaveDefermentRequest {
    export type DefermentTypeEnum = 'DEFERMENT' | 'CESSATION' | 'DEFERMENT_EXEC_SEIZURE' | 'DEFERMENT_EXEC_SALE' | 'DEFERMENT_EXEC_SEIZURE_SALE';
    export const DefermentTypeEnum = {
        Deferment: 'DEFERMENT' as DefermentTypeEnum,
        Cessation: 'CESSATION' as DefermentTypeEnum,
        DefermentExecSeizure: 'DEFERMENT_EXEC_SEIZURE' as DefermentTypeEnum,
        DefermentExecSale: 'DEFERMENT_EXEC_SALE' as DefermentTypeEnum,
        DefermentExecSeizureSale: 'DEFERMENT_EXEC_SEIZURE_SALE' as DefermentTypeEnum
    };
    export type HeaderFlagEnum = 'DRAFT' | 'SUBMIT' | 'APPROVE' | 'REJECT' | 'CANCEL' | 'DELETE' | 'UPDATE' | 'SUBMIT1' | 'SUBMIT2' | 'SAVE';
    export const HeaderFlagEnum = {
        Draft: 'DRAFT' as HeaderFlagEnum,
        Submit: 'SUBMIT' as HeaderFlagEnum,
        Approve: 'APPROVE' as HeaderFlagEnum,
        Reject: 'REJECT' as HeaderFlagEnum,
        Cancel: 'CANCEL' as HeaderFlagEnum,
        Delete: 'DELETE' as HeaderFlagEnum,
        Update: 'UPDATE' as HeaderFlagEnum,
        Submit1: 'SUBMIT1' as HeaderFlagEnum,
        Submit2: 'SUBMIT2' as HeaderFlagEnum,
        Save: 'SAVE' as HeaderFlagEnum
    };
}


