/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SeizureInfoDto { 
    ledId?: number;
    litigationCaseId?: number;
    seizureId?: number;
    seizureLedsId?: number;
    seizureTimestamp?: string;
    ledType?: string;
    auctionLawyerName?: string;
    courtName?: string;
    seizureType?: string;
}

