/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SeizureRequest { 
    amount?: number;
    blackCaseNo?: string;
    courtName?: string;
    imageId?: string;
    imageName?: string;
    ledName?: string;
    receiptBookNo?: string;
    receiptNo?: string;
    redCaseNo?: string;
}

