/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskActionHistoryDto } from './taskActionHistoryDto';


export interface TaskDetailDto { 
    /**
     * task assignee or task owner
     */
    approverId?: string;
    /**
     * approver full name
     */
    approverName?: string;
    /**
     * Some data that need to pass through between action on task
     */
    attributes?: string;
    /**
     * current approver id
     */
    createdBy?: string;
    /**
     * task created timestamp
     */
    createdTime?: string;
    /**
     * financial id related to this task
     */
    customerId?: string;
    /**
     * Amount of day(s) that this task need to be done
     */
    daysSla?: number;
    /**
     * total day spent on this task
     */
    daysSpent?: number;
    /**
     * task due date
     */
    dueDate?: string;
    /**
     * Enable task support role flag
     */
    enableTaskSupportRole?: boolean;
    /**
     * date on final action has been done
     */
    endDate?: string;
    /**
     * litigation case id related to this task
     */
    financialId?: string;
    /**
     * task s id
     */
    id?: number;
    /**
     * is hold flag
     */
    isHold?: boolean;
    /**
     * Latest draft user id 
     */
    latestDraftBy?: string;
    /**
     * Latest draft time
     */
    latestDraftTime?: string;
    /**
     * litigation id related to this task
     */
    litigationCaseId?: string;
    /**
     * litigation id related to this task
     */
    litigationId?: string;
    /**
     * task object id
     */
    objectId?: string;
    /**
     * task object type
     */
    objectType?: string;
    /**
     * task scope code
     */
    scopeCode?: string;
    /**
     * task scope name
     */
    scopeName?: string;
    /**
     * task start date
     */
    startDate?: string;
    /**
     * status code
     */
    statusCode?: string;
    /**
     * status name
     */
    statusName?: string;
    /**
     * List of an action has already done in this task
     */
    taskActionHistories?: Array<TaskActionHistoryDto>;
    /**
     * task type code
     */
    taskCode?: string;
    /**
     * task type name
     */
    taskName?: string;
    /**
     * customer id related to this task
     */
    userId?: string;
    /**
     * user full name
     */
    username?: string;
}

