/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDto { 
    amdResponseUnitCode?: string;
    amdResponseUnitName?: string;
    amdResponseUnitUserFullName?: string;
    amdResponseUnitUserId?: string;
    cifNumAndCustomerName?: string;
    countLitigation?: number;
    createdBy?: string;
    createdByName?: string;
    createdTime?: string;
    customerId?: string;
    daysExceedSla?: number;
    daysSla?: string;
    deptAmountInArrears?: number;
    displayAmdResponseUnit?: string;
    displayCFinalAndStage?: string;
    displayDeptAmountInArrears?: string;
    displayLgIdAndLitigationStatus?: string;
    displayResponseUnit?: string;
    displayTaskOwner?: string;
    displayTotalAmountInArrears?: string;
    dpd?: number;
    endDate?: string;
    firstName?: string;
    flowType?: string;
    lastName?: string;
    latestDraftBy?: string;
    latestDraftByName?: string;
    latestDraftTime?: string;
    lawyerOfficeCode?: string;
    lawyerOfficeName?: string;
    limitAmount?: number;
    litigationDate?: string;
    litigationDescBody?: string;
    litigationDescHeader?: string;
    litigationId?: string;
    litigationStatusCode?: string;
    litigationStatusName?: string;
    multipleLitigation?: boolean;
    name?: string;
    objectId?: string;
    objectType?: string;
    personType?: string;
    prescriptionDate?: string;
    responseUnitCode?: string;
    responseUnitName?: string;
    responseUnitUserFullName?: string;
    responseUnitUserId?: string;
    sla?: number;
    slaTypeCode?: string;
    statusCode?: string;
    statusName?: string;
    taskCode?: string;
    taskId?: number;
    taskName?: string;
    title?: string;
    totalAmountInArrears?: number;
    totalDebt?: number;
    userId?: string;
}

