/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiveTransactionDto } from './receiveTransactionDto';
import { TransferTransactionDto } from './transferTransactionDto';


export interface TransferOrderDto { 
    blackCaseNo?: string;
    branchCode?: string;
    branchName?: string;
    courtCode?: string;
    courtName?: string;
    courtRefundAmount?: number;
    litigationCaseId?: number;
    litigationId?: string;
    litigationStatus?: string;
    litigationStatusName?: string;
    mainBorrowerPersonId?: string;
    mainBorrowerPersonName?: string;
    orgCode?: string;
    orgName?: string;
    receiveTransactions?: Array<ReceiveTransactionDto>;
    redCaseNo?: string;
    responseUnitCode?: string;
    responseUnitName?: string;
    sumClearingAmount?: number;
    transferTransactions?: Array<TransferTransactionDto>;
}

