/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawSeizureLedDto } from './withdrawSeizureLedDto';


export interface WithdrawSeizureLedAllResponse { 
    actorId?: string;
    actorName?: string;
    createdTimestamp?: string;
    debtPaidAmount?: number;
    isContactResponseForExpense?: boolean;
    litigationCaseId?: number;
    reasonWithdrawSeizures?: string;
    status?: string;
    withdrawSeizureId?: number;
    withdrawSeizureLed?: WithdrawSeizureLedDto;
    withdrawSeizureLeds?: Array<WithdrawSeizureLedDto>;
    withdrawSeizureSeq?: number;
    withdrawSeizureType?: string;
}

