/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LedDocumentDto } from './ledDocumentDto';
import { WithdrawSeizureGroups } from './withdrawSeizureGroups';


export interface WithdrawSeizureLedDto { 
    withdrawSeizureLedId?: number;
    civilCourtNo?: string;
    civilCourtName?: string;
    ledId?: number;
    ledName?: string;
    ledRefNo?: string;
    ledRefNoDate?: string;
    publicAuctionLawyerId?: string;
    publicAuctionLawyerName?: string;
    status?: string;
    resultDate?: string;
    withdrawSeizureLedDocuments?: Array<LedDocumentDto>;
    withdrawSeizureLedGroups?: Array<WithdrawSeizureGroups>;
}

