/**
 * KTB Backend for Frontend APIs.
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WithdrawSeizureCollateralInfo { 
    collateralId?: string;
    collateralType?: string;
    collateralSubType?: string;
    documentNo?: string;
    collateralDetails?: string;
    ownerName?: string;
    totalAppraisalValue?: number;
    ledName?: string;
    status?: string;
    ledRefNo?: string;
    obligationStatus?: string;
}

