import { AccountDto, CollateralDto  } from "@lexs/lexs-client";
import { PreferenceDto } from "./preference-detail.interface";
import { IUploadMultiFile } from "@app/shared/models";
import { InquiryCustomerResponse } from "@lexs/lexs-client";

export const mockCustomerDto: InquiryCustomerResponse = {
  // accountNoList: "1234567890,0987654321",
  // amdResponseUnitCode: "AMD001",
  // amdResponseUnitName: "Unit Name 1",
  // amdResponseUserId: "USER001",
  // amdResponseUserName: "John Doe",
  // billNoList: "BILL001,BILL002",
  cifNo: "CIF123456789",
  // customerId: "CUST001",
  // displayAmdResponseUnit: "Display Unit Name 1",
  // displayAmdResponseUser: "Display John Doe",
  // displayResponseUnit: "Display Unit Name 2",
  // displayResponseUser: "Display Jane Doe",
  // exportLitigationList: "LIT001,LIT002",
  // litigationList: "CASE001,CASE002",
  // loanTypeCode: "LOAN001",
  // maxStageAccount: "Stage001",
  // prescriptionDate: "2024-01-01",
  // responseUserId: "USER002",
  // responseUserName: "Jane Doe",
  // rmUserId: "RM001",
  fullName: "Customer Name",
  dpd: 11111,
  cfinalStage: "111",
  responseUnitCode: "RESP001",
  responseUnitName: "Jane Doe",
  amdResponseUnitCode: "AMD001",
  amdResponseUnitName: "Unit Name 1",
  branchCode: "BR001",
  branchName: "branchName",
};

export const mockAccountDto: AccountDto = {
  accountId: 'ACC001',
  accountName: 'Main Account',
  accountNo: '1234567890',
  accountNote: 'This is a mock account.',
  accountStatus: 'Active',
  // accountType: 'SAVINGS',
  amountInArrears: 5000.75,
  billNo: 'BILL001',
  blackCaseNo: 'CASE001',
  bookingCode: 'BOOK001',
  bookingName: 'Main Booking',
  branchCode: 'BR001',
  branchName: 'Head Branch',
  cfinal: 'FinalStage1',
  closeDate: '2024-01-15',
  commitmentAccountNo: 'COMMIT12345',
  contractDate: '2020-03-01',
  customerId: 'CUST001',
  deliquencyDate: '2023-12-01',
  directDebitAccountNumber: '9876543210',
  dpd: 30,
  estimatePrescriptionFlag: true,
  expiryDate: '2025-12-31',
  firstDisbursementDate: '2019-07-01',
  interestNonBook: 100.25,
  lastDisburseDate: '2023-01-01',
  lastPaidDate: '2023-11-15',
  lastTransactionDate: '2023-12-10',
  lastUpdate: '2024-01-01',
  lateChargeAmount: 50.5,
  lgAccountName: 'LG Account',
  lgAccountNumber: 'LG987654',
  limitAmount: 100000.0,
  litigationId: 'LIT001',
  litigationStatus: 'In Progress',
  marketCode: 'MKT001',
  marketDescription: 'High Value Market',
  miscCharge: 25.0,
  newSubAccount: true,
  noticeContractName: 'Notice Contract 1',
  openDate: '2018-06-01',
  outstandingAccruedInterest: 200.75,
  outstandingBalance: 15000.0,
  partialWriteOffFlag: 'N',
  partialWriteOffStatus: 'None',
  prescriptionDate: '2024-06-30',
  primaryAccountNumber: 'PRIMARY001',
  productType: 'Loan',
  projectName: 'Project Alpha',
  redCaseNo: 'RED001',
  responseBranchCode: 'RESP001',
  responseBranchName: 'Response Branch',
  samFlag: 'Y',
  sourceSystem: 'SystemA',
  stageFinal: 'Stage3',
  subAccount: false,
  subAccountOption: 'Option1',
  subAccountType: 'TypeA',
  tamcFlag: 'N',
  tdrContractDate: '2023-01-01',
  tdrDate: '2023-06-15',
  tdrStatus: 'Active',
  tdrTrackingResult: 'Successful',
  userName: 'John Doe',
  writeDate: '2023-12-31',
  writeOffStatus: 'Closed',
};

export const mockCollateralDto: CollateralDto = {
  accountGroup: 'Group001',
  accountName: 'Main Account',
  accountNo: 'ACC123456',
  accounts: ['ACC123456', 'ACC789012'],
  address1: '123 Main Street',
  address2: 'Building B',
  address3: 'Suite 101',
  appraisalDate: '2024-01-01',
  appraisalPrice: 500000,
  appraisalValue: 450000,
  areaNgan: 3,
  areaRai: 1,
  areaSqm: 100,
  areaSqrWa: 4,
  bankName: 'KTB Bank',
  blackCaseNo: 'CASE12345',
  bondNo: 'BOND001',
  bondNo2: 'BOND002',
  bookNo: 'BK001',
  bookingValue: 300000,
  borrower: 'John Doe',
  botCode: 'BOT001',
  botSubCode: 'SUBBOT001',
  buildingFloors: '5',
  buildingName: 'Alpha Tower',
  buildingNo: 'B1',
  buyerName: 'Jane Doe',
  calculatedCollateralStatus: 'Active',
  cifNo: 'CIF123456',
  collateralContractStatus: 'Ongoing',
  collateralId: 'COL001',
  collateralStatusCode: 'CS001',
  collateralStatusDesc: 'Secured',
  collateralSubTypeCode: 'CST001',
  collateralSubTypeDesc: 'Subtype Desc',
  collateralTypeCode: 'CT001',
  collateralTypeDesc: 'Type Desc',
  commodityDesc: 'Electronics',
  consignmentAmount: 150000,
  consignmentSellerName: 'ElectroMart',
  contractDate: '2023-12-01',
  contractId: 'CON123456',
  contractStatus: 'Active',
  court: 'Central Court',
  currency: 'THB',
  description: 'Collateral Description Example',
  district: 'Central District',
  districtCode: 'D001',
  documentNo: 'DOC123456',
  dueDate: '2024-06-30',
  employerName: 'ABC Corp',
  employerType: 'Private',
  engineNo: 'ENG123456',
  estimateFreezeAmount: 200000,
  expropriate: 'No',
  expropriateAmount: 0,
  expropriatePerson: '',
  externalAssetStatus: 'Secured',
  externalAssetStatusDesc: 'Fully Secured',
  floor: '3rd',
  foundPropertyProcessType: 'Type A',
  foundPropertyRemark: 'No issues found',
  freezeDate: '2024-02-01',
  insurancePolicyNumber: 'POL123456',
  issueDate: '2023-01-01',
  issuer: 'Insurance Co',
  jobPosition: 'Manager',
  landNo: 'LN001',
  leasePeriod: 12,
  legalStatus: 'Verified',
  legalStatusDesc: 'Legal verification completed',
  lendContractNo: 'LCN123456',
  lendDate: '2023-10-01',
  lendProduct: 'Loan',
  lendType: 'Type A',
  lender: 'KTB Bank',
  litigationId: 'LIT001',
  machineAmount: 200000,
  machineName: 'Lathe Machine',
  machineNo: 'MCH123456',
  machineNo2: 'MCH654321',
  mortgageAmount: 250000,
  mortgageeName: 'John Smith',
  notTransferOwnershipFromDate: '2023-05-01',
  notTransferOwnershipToDate: '2024-05-01',
  notTransferOwnershipWithin: 12,
  obligationStatus: 'Active',
  obligationType: 'Type A',
  otherIncome: 5000,
  otherLitigationId: 'LIT002',
  ownerId: 'OWN001',
  ownerName: 'Jane Smith',
  parValue: 100,
  pawnAmount: 15000,
  pawnName: 'Pawn Shop 1',
  payerOrganization: 'KTB Finance',
  paymentType: 'Installment',
  personId: 'PID123456',
  priceValue: 100000,
  projectName: 'Project Alpha',
  province: 'Bangkok',
  provinceCode: 'P001',
  ravang: '12345',
  redCaseNo: 'RED001',
  redeemPeriod: 24,
  registrationNo: 'REG123456',
  remainingPeriod: 18,
  remark: 'No remarks',
  rentalFee: 2000,
  roomNo: '101',
  salary: 50000,
  seizureDate: '2023-12-15',
  seizurePerson: 'Officer A',
  seizureRedCaseNo: 'RED123456',
  serviceMonth: 12,
  serviceYear: 2023,
  sourceSystem: 'SYS001',
  subDistrict: 'Sub Central',
  subdistrictCode: 'SD001',
  surveySection: 'Section A',
  tcg: true,
  totalAppraisalValue: 600000,
  typeDescription: 'Land',
  typeOfContract: 'Type A',
  typeOfContractOrder: 'Order001',
  unit: 'sqm',
  unitAmount: 150,
  updateFlag: 'A',
  vehicleCount: 5,
  vehicleNo: 'VH123456',
  weight: 1500,
  workOrganization: 'Work Co.',
};

export const mockPreferenceDto: PreferenceDto = {
  preferenceId: 'PREF001',
  executeType: 'Execution',
  executeDate: '2024-01-01',
  receivedDate: '2024-01-05',
  executeNo: 'WRIT2024001',
  ledId: 'Bangkok Central Office',
  blackCaseNo: 'CASE12345BLACK',
  elementRedCaseCiosCode: 'Civil',
  elementRedCaseRunning: 'CASE12345',
  elementRedCaseYear: '2024',
  executeCaseType: 'Seizure',
  plaintiffName: 'John Doe',
  courtCode: 'Bangkok District Court',
  nonFilingReason: 'No response from debtor',
  sell: 'Auction',
  customer: mockCustomerDto,
  accounts: [mockAccountDto],
  collaterals: [mockCollateralDto],
};

// export const mockPreferenceDto: PreferenceDto = {
//   preferenceId: 'PREF001',
//   executeType: 'Execution',
//   executeDate: '2024-01-01',
//   receivedDate: '2024-01-05',
//   executeNo: 'WRIT2024001',
//   ledId: 'Bangkok Central Office',
//
//   blackCaseNo: 'CASE12345BLACK',
//   category: 'Civil',
//   caseNumber: 'CASE12345',
//   year: '2024',
//   orderType: 'Seizure',
//
//   externalPlaintiffCaseNumber: 'EXTCASE98765',
//   plaintiffName: 'John Doe',
//   court: 'Bangkok District Court',
//   nonFilingReason: 'No response from debtor',
//   saleMethod: 'Auction',
//
//   customerDto: mockCustomerDto,
//   accountDtos: [mockAccountDto],
//   collateralDtos: [mockCollateralDto],
// };

export const mockCustomerDtos: InquiryCustomerResponse[] = [
  mockCustomerDto,
  {
    // accountNoList: "1122334455,5566778899",
    // amdResponseUnitCode: "AMD002",
    // amdResponseUnitName: "Unit Name 2",
    // amdResponseUserId: "USER002",
    // amdResponseUserName: "Alice Smith",
    // billNoList: "BILL003,BILL004",
    // branchCode: "BR002",
    cifNo: "CIF987654321",
    // customerId: "CUST002",
    // displayAmdResponseUnit: "Display Unit Name 2",
    // displayAmdResponseUser: "Display Alice Smith",
    // displayResponseUnit: "Display Unit Name 3",
    // displayResponseUser: "Display Bob Jones",
    // exportLitigationList: "LIT003,LIT004",
    // litigationList: "CASE003,CASE004",
    // loanTypeCode: "LOAN002",
    // maxCFinal: "Final002",
    // maxStageAccount: "Stage002",
    // name: "Another Customer",
    // prescriptionDate: "2023-12-31",
    // responseUnitCode: "RESP002",
    // responseUnitName: "Response Unit 2",
    // responseUserId: "USER003",
    // responseUserName: "Bob Jones",
    // rmUserId: "RM002",
    // maxDpd: 9999,
    fullName: "Customer Name",
    dpd: 11111,
    cfinalStage: '111',
    responseUnitCode: "RESP001",
    responseUnitName: "Jane Doe",
    amdResponseUnitCode: "AMD001",
    amdResponseUnitName: "Unit Name 1",
    branchCode: "BR001",
    branchName: "branchName",
  },
  {
    // accountNoList: "2233445566,7788990011",
    // amdResponseUnitCode: "AMD003",
    // amdResponseUnitName: "Unit Name 3",
    // amdResponseUserId: "USER003",
    // amdResponseUserName: "Charlie Brown",
    // billNoList: "BILL005,BILL006",
    // branchCode: "BR003",
    cifNo: "CIF112233445",
    // customerId: "CUST003",
    // displayAmdResponseUnit: "Display Unit Name 3",
    // displayAmdResponseUser: "Display Charlie Brown",
    // displayResponseUnit: "Display Unit Name 4",
    // displayResponseUser: "Display Dana White",
    // exportLitigationList: "LIT005,LIT006",
    // litigationList: "CASE005,CASE006",
    // loanTypeCode: "LOAN003",
    // maxCFinal: "Final003",
    // maxStageAccount: "Stage003",
    // name: "Third Customer",
    // prescriptionDate: "2024-02-15",
    // responseUnitCode: "RESP003",
    // responseUnitName: "Response Unit 3",
    // responseUserId: "USER004",
    // responseUserName: "Dana White",
    // rmUserId: "RM003",
    // maxDpd: 5555,
    fullName: "Customer Name",
    dpd: 222,
    cfinalStage: '222',
    responseUnitCode: "RESP002",
    responseUnitName: "Jane Doe",
    amdResponseUnitCode: "AMD002",
    amdResponseUnitName: "Unit Name 2",
    branchCode: "BR002",
    branchName: "branchName",
  },
];
export const mockAccountDtos: AccountDto[] = [mockAccountDto];
export const mockCollateralDtos: CollateralDto[] = [mockCollateralDto];

export const DEFAULT_DOCUMENT_REQUEST_ORIGINAL_DEED_AUCTION_ANNOUNCEMENT = [
  {
    documentTemplate: {
      documentName: 'หนังสือให้ส่งต้นฉบับโฉนด/ประกาศขายทอดตลาด',
    },
    documentTemplateId: '', // TODO ADD DOC_TEMPLATE AS TEMPLATE ID
    uploadRequired: true,
    viewOnly: true,
    removeDocument: true,
  } as IUploadMultiFile,
];
